-- Clean database

DROP TABLE CLICK IF EXISTS;
DROP TABLE SHORTURL IF EXISTS;

-- ShortURL

CREATE TABLE SHORTURL(
	HASH		VARCHAR(30) PRIMARY KEY,	-- Key
	TARGET		VARCHAR(1024),				-- Original URL
	SPONSOR		VARCHAR(1024),				-- Sponsor URL
	CREATED 	TIMESTAMP,					-- Creation date
	OWNER		VARCHAR(255),				-- User id
	MODE		INTEGER,					-- Redirect mode
	SAFE		BOOLEAN,						-- Safe target
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50),					-- Country
	QRAPI		VARCHAR(1024),				--QR CODE API QUERY
	QRCODE		VARCHAR(8000),				--QR CODE IN BASE 64
	TIEMPO      VARCHAR(200)                --PUBLICIDAD
);

-- Click

CREATE TABLE CLICK(
  ID 			BIGINT IDENTITY,			-- KEY
	HASH 		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	-- Foreing key
	CREATED 	TIMESTAMP,					-- Creation date
	REFERRER	VARCHAR(1024),				-- Traffic origin
	BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50),					-- Country
	COMUNITY  VARCHAR(50),         --Comunity
	CITY		VARCHAR(50),				--City
	LATITUD		VARCHAR(30),				--Latitud
	LONGITUD	VARCHAR(30)					--Longitud
)